// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID          pgtype.UUID
	Name        string
	Email       string
	Cpf         string
	CarPlate    pgtype.Text
	IsPassenger bool
	IsDriver    bool
}

type Ride struct {
	ID          pgtype.UUID
	PassengerID pgtype.UUID
	DriverID    pgtype.UUID
	Status      string
	Fare        pgtype.Numeric
	Distance    pgtype.Numeric
	FromLat     pgtype.Numeric
	FromLong    pgtype.Numeric
	ToLat       pgtype.Numeric
	ToLong      pgtype.Numeric
	Date        pgtype.Timestamp
}
