// Code generated by scaffold. DO NOT EDIT.

package domain

import "github.com/eduardonunesp/cleanarchgo/pkg/domain/valueobject"

type accountOption func(*Account) error

func BuildAccount(options ...accountOption) (*Account, error) {
	newAccount := Account{}
	for _, opt := range options {
		if err := opt(&newAccount); err != nil {
			return nil, RaiseDomainError(err)
		}
	}
	return &newAccount, nil
}

func AccountWithID(id string) accountOption {
	return func(opt *Account) error {
		var err error
		opt.id, err = valueobject.UUIDFromString(id)
		return err
	}
}

func AccountWithNewID() accountOption {
	return func(opt *Account) error {
		opt.id = valueobject.MustUUID()	
		return nil
	}
}

func AccountWithName(name string) accountOption {
	return func(opt *Account) error {
		var err error
		opt.name, err = valueobject.NameFromString(name)
		return err
	}
}

func AccountWithEmail(email string) accountOption {
	return func(opt *Account) error {
		var err error
		opt.email, err = valueobject.EmailFromString(email)
		return err
	}
}

func AccountWithCpf(cpf string) accountOption {
	return func(opt *Account) error {
		var err error
		opt.cpf, err = valueobject.CpfFromString(cpf)
		return err
	}
}

func AccountWithCarPlate(carPlate string) accountOption {
	return func(opt *Account) error {
		var err error
		opt.carPlate, err = valueobject.CarPlateFromString(carPlate)
		return err
	}
}

func AccountWithHash(hash string) accountOption {
	return func(opt *Account) error {
		var err error
		opt.hash, err = valueobject.LoadHashFromString(hash)
		return err
	}
}

func AccountWithEncodedHash(hash string) accountOption {
	return func(opt *Account) error {
		var err error
		opt.hash, err = valueobject.BuildHashFromString(hash, nil)
		return err
	}
}

func AccountWithAccountType(accountType string) accountOption {
	return func(opt *Account) error {
		var err error
		opt.accountType, err = valueobject.AccountTypeFromString(accountType)
		return err
	}
}

func AccountWithConfirmedAt(confirmedAt int64) accountOption {
	return func(opt *Account) error {
		var err error
		opt.confirmedAt, err = valueobject.DateFromUnix(confirmedAt)
		return err
	}
}

func AccountWithCreatedAt(createdAt int64) accountOption {
	return func(opt *Account) error {
		var err error
		opt.createdAt, err = valueobject.DateFromUnix(createdAt)
		return err
	}
}

func AccountWithUpdatedAt(updatedAt int64) accountOption {
	return func(opt *Account) error {
		var err error
		opt.updatedAt, err = valueobject.DateFromUnix(updatedAt)
		return err
	}
}
