// Code generated by scaffold. DO NOT EDIT.

package domain

import "github.com/eduardonunesp/cleanarchgo/pkg/domain/valueobject"

type positionOption func(*Position) error

func BuildPosition(options ...positionOption) (*Position, error) {
	newPosition := Position{}
	for _, opt := range options {
		if err := opt(&newPosition); err != nil {
			return nil, RaiseDomainError(err)
		}
	}
	return &newPosition, nil
}

func PositionWithID(id string) positionOption {
	return func(opt *Position) error {
		var err error
		opt.id, err = valueobject.UUIDFromString(id)
		return err
	}
}

func PositionWithNewID() positionOption {
	return func(opt *Position) error {
		opt.id = valueobject.MustUUID()	
		return nil
	}
}

func PositionWithRideID(rideId string) positionOption {
	return func(opt *Position) error {
		var err error
		opt.rideID, err = valueobject.UUIDFromString(rideId)
		return err
	}
}

func PositionWithNewRideID() positionOption {
	return func(opt *Position) error {
		opt.rideID = valueobject.MustUUID()	
		return nil
	}
}

func PositionWithCoord(x, y string) positionOption {
	return func(p *Position) error {
		var err error
		p.coord, err = valueobject.BuildCoord(x, y)
		return err
	}
}

func PositionWithDate(date int64) positionOption {
	return func(opt *Position) error {
		var err error
		opt.date, err = valueobject.DateFromUnix(date)
		return err
	}
}
