quiet: True
with-expecter: True 
outPkg: "test"
filename: "Mock{{.InterfaceName}}.go"
mockname: "Mock{{.InterfaceName}}"
packages:
  github.com/eduardonunesp/cleanarchgo/pkg/infra/repository:
    config: 
      dir: ../../test/
    interfaces:
      AccountRepositoryRO:
      RideRepositoryRO:
      PositionRepositoryRO:
      AccountRepository:
      RideRepository:
      PositionRepository:
  github.com/eduardonunesp/cleanarchgo/pkg/infra/gateway:
    config: 
      dir: ../../test/
    interfaces:
      MailerGW: