// Code generated by mockery v2.42.2. DO NOT EDIT.

package test

import (
	domain "github.com/eduardonunesp/cleanarchgo/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockPositionRepository is an autogenerated mock type for the PositionRepository type
type MockPositionRepository struct {
	mock.Mock
}

type MockPositionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPositionRepository) EXPECT() *MockPositionRepository_Expecter {
	return &MockPositionRepository_Expecter{mock: &_m.Mock}
}

// GetPositionsByRideID provides a mock function with given fields: rideID
func (_m *MockPositionRepository) GetPositionsByRideID(rideID string) ([]*domain.Position, error) {
	ret := _m.Called(rideID)

	if len(ret) == 0 {
		panic("no return value specified for GetPositionsByRideID")
	}

	var r0 []*domain.Position
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*domain.Position, error)); ok {
		return rf(rideID)
	}
	if rf, ok := ret.Get(0).(func(string) []*domain.Position); ok {
		r0 = rf(rideID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Position)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(rideID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPositionRepository_GetPositionsByRideID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPositionsByRideID'
type MockPositionRepository_GetPositionsByRideID_Call struct {
	*mock.Call
}

// GetPositionsByRideID is a helper method to define mock.On call
//   - rideID string
func (_e *MockPositionRepository_Expecter) GetPositionsByRideID(rideID interface{}) *MockPositionRepository_GetPositionsByRideID_Call {
	return &MockPositionRepository_GetPositionsByRideID_Call{Call: _e.mock.On("GetPositionsByRideID", rideID)}
}

func (_c *MockPositionRepository_GetPositionsByRideID_Call) Run(run func(rideID string)) *MockPositionRepository_GetPositionsByRideID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPositionRepository_GetPositionsByRideID_Call) Return(_a0 []*domain.Position, _a1 error) *MockPositionRepository_GetPositionsByRideID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPositionRepository_GetPositionsByRideID_Call) RunAndReturn(run func(string) ([]*domain.Position, error)) *MockPositionRepository_GetPositionsByRideID_Call {
	_c.Call.Return(run)
	return _c
}

// SavePosition provides a mock function with given fields: position
func (_m *MockPositionRepository) SavePosition(position *domain.Position) error {
	ret := _m.Called(position)

	if len(ret) == 0 {
		panic("no return value specified for SavePosition")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Position) error); ok {
		r0 = rf(position)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPositionRepository_SavePosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SavePosition'
type MockPositionRepository_SavePosition_Call struct {
	*mock.Call
}

// SavePosition is a helper method to define mock.On call
//   - position *domain.Position
func (_e *MockPositionRepository_Expecter) SavePosition(position interface{}) *MockPositionRepository_SavePosition_Call {
	return &MockPositionRepository_SavePosition_Call{Call: _e.mock.On("SavePosition", position)}
}

func (_c *MockPositionRepository_SavePosition_Call) Run(run func(position *domain.Position)) *MockPositionRepository_SavePosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Position))
	})
	return _c
}

func (_c *MockPositionRepository_SavePosition_Call) Return(_a0 error) *MockPositionRepository_SavePosition_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPositionRepository_SavePosition_Call) RunAndReturn(run func(*domain.Position) error) *MockPositionRepository_SavePosition_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPositionRepository creates a new instance of MockPositionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPositionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPositionRepository {
	mock := &MockPositionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
